### PR TITLE
Added new css setting 'allContainerCssClass'

### PR DESCRIPTION
**Pull request by whardeman**
Thoughts on this?

### CODE REVIEW

**Comment by insin** [comment]
Looks good

It's fiddly handing over all rendering to newforms - the long-term goal is to move to a templated approach (and remove the hard dependency on DOMBuilder) or some other method which hands you all the bits of data required for custom rendering, but there's no harm in making it a bit more configurable in the meantime.

Will add some tests and merge in later.

**Comment by whardeman** [comment]
That sounds great. I have worked with Django forms for a long time and really like its default rendering with the ability to customize with templates. This is great stuff...thanks again.

**Comment by insin** [comment]
Merged in 8e552d19594508ea7d9befea3da3741af4dacff8

I changed the name of the property to `rowCssClass` and made it appear first in c40e501db63c52bcbff37bb124857819e6fd95f0 - "row" is a bit weird because it only technically applies to the table rendering, but it's terminology that's already out there.

Cheers!

**Comment by whardeman** [comment]
Super!

**Pull request closed without merging**
