### PR TITLE
Deletion fix

### PR DESCRIPTION
**Pull request by whardeman**
While you're at it, have a look at this and give me your feedback...

Hope I'm not being to bold here...I'm using this module extensively and found a few things that drive me a bit batty. Thought I'd share. :)

### CODE REVIEW

**Comment by whardeman** [comment]
Drat. I seem to have added both recent commits to this pull request.

**Comment by whardeman** [comment]
There we go...that fixed it.

**Comment by insin** [comment]
I'll have a muck about with this via the tests when I get some time - I'd imagine this is something that could be back-ported to Django if it's a pain point in FormSets :)

**Comment by insin** [comment]
Linking relevant Django ticket for future reference:

https://code.djangoproject.com/ticket/9061

**Comment by insin** [comment]
Ok, these both look good - will have a go at a bit of rebase magic later to split them up into two commits and add tests.

**Pull request merged**
